name: Build and Push Docker Images

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Debug Secret Access
        run: |
          if [ -z "${{ secrets.DOCKER_HUB_USERNAME }}" ]; then
            echo "DOCKER_HUB_USERNAME is NOT set"
            exit 1
          else
            echo "DOCKER_HUB_USERNAME is set"
          fi

          if [ -z "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" ]; then
            echo "DOCKER_HUB_ACCESS_TOKEN is NOT set"
            exit 1
          else
            echo "DOCKER_HUB_ACCESS_TOKEN is set"
          fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Clients image
        uses: docker/build-push-action@v4
        with:
          context: ./Clients
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/verifywise-frontend:latest

      - name: Build and push Servers image
        uses: docker/build-push-action@v4
        with:
          context: ./Servers
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/verifywise-backend:latest
